//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SportCentre.MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Lesson
    {
        public int Id { get; set; }
        public Nullable<int> IdGroup { get; set; }
        public Nullable<System.TimeSpan> Beginning { get; set; }
        public Nullable<int> Duration { get; set; }
        public Nullable<int> IdTrainer { get; set; }
        public Nullable<int> IdGym { get; set; }
    
        public virtual Group Group { get; set; }
        public virtual Gym Gym { get; set; }
        public virtual Trainer Trainer { get; set; }
    }
}
