//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SportCentre.MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Membership
    {
        public int Id { get; set; }
        public Nullable<int> IdGroup { get; set; }
        public int IdClient { get; set; }
        public Nullable<int> IdSubscription { get; set; }
        public System.DateTime ExpirationDate { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual Group Group { get; set; }
        public virtual Subscription Subscription { get; set; }
    }
}
